import sys

new_methods = (
  "\n  // ── AI-4: Counterfeit Packaging Multi-Factor Analyzer ─────────────────────\n"
  "  Future<CounterfeitAnalysisResult> analyzeCounterfeitRisk(\n"
  "    dynamic imageInput, {\n"
  "    Uint8List? bytes,\n"
  "    String? expectedMedicineName,\n"
  "    String? expectedBatchNumber,\n"
  "  }) async {\n"
  "    if (!_initialized || _model == null) return _fallbackCounterfeitAnalysis();\n"
  "    try {\n"
  "      Uint8List imgBytes;\n"
  "      if (bytes != null) {\n"
  "        imgBytes = bytes;\n"
  "      } else if (imageInput is Uint8List) {\n"
  "        imgBytes = imageInput;\n"
  "      } else if (imageInput != null) {\n"
  "        try { imgBytes = await imageInput.readAsBytes(); }\n"
  "        catch (_) { imgBytes = await File(imageInput.path).readAsBytes(); }\n"
  "      } else {\n"
  "        return _fallbackCounterfeitAnalysis();\n"
  "      }\n"
  "      final ctx = [\n"
  "        if (expectedMedicineName != null) 'Expected medicine: ' + expectedMedicineName!,\n"
  "        if (expectedBatchNumber != null) 'Expected batch: ' + expectedBatchNumber!,\n"
  "      ].join('\\n');\n"
  "      final prompt = 'Pharmaceutical counterfeit detection specialist. Analyze packaging image for authenticity. '\n"
  "          + (ctx.isNotEmpty ? 'Context: ' + ctx + ' ' : '')\n"
  "          + 'Score each 0-10 (10=authentic): print_quality, seal_integrity, font_consistency, label_alignment, color_accuracy. '\n"
  "          + 'Also: overall_risk (LOW/MEDIUM/HIGH), risk_score (0-100 where 0=authentic), '\n"
  "          + 'primary_concern (string or null), is_tampered (bool). '\n"
  "          + 'JSON only: {\"print_quality\":9,\"seal_integrity\":8,\"font_consistency\":9,\"label_alignment\":9,\"color_accuracy\":9,\"overall_risk\":\"LOW\",\"risk_score\":5,\"primary_concern\":null,\"is_tampered\":false}';\n"
  "      final content = [Content.multi([TextPart(prompt), DataPart('image/jpeg', imgBytes)])];\n"
  "      final response = await _model!.generateContent(content).timeout(const Duration(seconds: 15));\n"
  "      final jsonMatch = RegExp(r'\\{[\\s\\S]*\\}').firstMatch(response.text ?? '');\n"
  "      if (jsonMatch != null) {\n"
  "        final d = json.decode(jsonMatch.group(0)!) as Map<String, dynamic>;\n"
  "        return CounterfeitAnalysisResult(\n"
  "          printQuality: (d['print_quality'] as num?)?.toDouble() ?? 8,\n"
  "          sealIntegrity: (d['seal_integrity'] as num?)?.toDouble() ?? 8,\n"
  "          fontConsistency: (d['font_consistency'] as num?)?.toDouble() ?? 8,\n"
  "          labelAlignment: (d['label_alignment'] as num?)?.toDouble() ?? 8,\n"
  "          colorAccuracy: (d['color_accuracy'] as num?)?.toDouble() ?? 8,\n"
  "          overallRisk: d['overall_risk'] as String? ?? 'LOW',\n"
  "          riskScore: d['risk_score'] as int? ?? 5,\n"
  "          primaryConcern: d['primary_concern'] as String?,\n"
  "          isTampered: d['is_tampered'] as bool? ?? false,\n"
  "          isAiAnalyzed: true,\n"
  "        );\n"
  "      }\n"
  "    } catch (e) {\n"
  "      debugPrint('Counterfeit analysis error: ' + e.toString());\n"
  "    }\n"
  "    return _fallbackCounterfeitAnalysis();\n"
  "  }\n"
  "\n"
  "  CounterfeitAnalysisResult _fallbackCounterfeitAnalysis() =>\n"
  "      const CounterfeitAnalysisResult(\n"
  "        printQuality: 8, sealIntegrity: 8, fontConsistency: 8,\n"
  "        labelAlignment: 8, colorAccuracy: 8, overallRisk: 'LOW',\n"
  "        riskScore: 10, primaryConcern: null, isTampered: false, isAiAnalyzed: false,\n"
  "      );\n"
  "\n"
  "  // ── AI-5: Sentinel Natural Language Query ─────────────────────────────────\n"
  "  Future<String> sentinelQuery({\n"
  "    required String question,\n"
  "    required List<FraudAlert> alerts,\n"
  "    required Map<String, int> systemStats,\n"
  "  }) async {\n"
  "    if (!_initialized || _model == null) return _offlineSentinelResponse(question, alerts, systemStats);\n"
  "    try {\n"
  "      final alertSummary = alerts.take(20).map((a) =>\n"
  "          '[' + a.severity + '] ' + a.alertTypeLabel + ' Batch ' + (a.batchNumber ?? '?') + ' ' + a.status).join(', ');\n"
  "      final statsText = systemStats.entries.map((e) => e.key + ': ' + e.value.toString()).join(', ');\n"
  "      final prompt = 'CDSCO Sentinel AI analytics assistant. Answer question using ONLY the data. 2-4 sentences. Do not invent data.\\n'\n"
  "          'Stats: ' + statsText + '\\nAlerts: ' + alertSummary + '\\nQuestion: ' + question + '\\nAnswer:';\n"
  "      final response = await _model!.generateContent([Content.text(prompt)]).timeout(const Duration(seconds: 10));\n"
  "      final result = response.text?.trim();\n"
  "      if (result != null && result.isNotEmpty) return result;\n"
  "    } catch (e) {\n"
  "      debugPrint('Sentinel query error: ' + e.toString());\n"
  "    }\n"
  "    return _offlineSentinelResponse(question, alerts, systemStats);\n"
  "  }\n"
  "\n"
  "  String _offlineSentinelResponse(String question, List<FraudAlert> alerts, Map<String, int> systemStats) {\n"
  "    final openAlerts = alerts.where((a) => a.status == 'OPEN').length;\n"
  "    final criticals = alerts.where((a) => a.isCritical).length;\n"
  "    final q = question.toLowerCase();\n"
  "    if (q.contains('critical') || q.contains('serious')) {\n"
  "      return criticals.toString() + ' critical alerts require immediate CDSCO inspector action.';\n"
  "    }\n"
  "    if (q.contains('open') || q.contains('pending')) {\n"
  "      return openAlerts.toString() + ' alerts are currently open and awaiting investigation.';\n"
  "    }\n"
  "    return (systemStats['EXPIRED'] ?? 0).toString() + ' batches are EXPIRED. '\n"
  "        + (systemStats['ACTIVE'] ?? 0).toString() + ' are ACTIVE in the system.';\n"
  "  }\n"
  "\n"
  "  // ── AI-6: Smart Expiry Risk Narrative ────────────────────────────────────\n"
  "  Future<String> generateExpiryRiskBriefing({\n"
  "    required int expiringCount,\n"
  "    required int expiredCount,\n"
  "    required int criticalRiskCount,\n"
  "    required String organizationName,\n"
  "  }) async {\n"
  "    if (!_initialized || _model == null || (expiringCount == 0 && expiredCount == 0)) {\n"
  "      return _offlineExpiryBriefing(expiringCount: expiringCount, expiredCount: expiredCount,\n"
  "          criticalRiskCount: criticalRiskCount, organizationName: organizationName);\n"
  "    }\n"
  "    try {\n"
  "      final prompt = 'Generate a 2-sentence compliance briefing for ' + organizationName + '. '\n"
  "          + expiredCount.toString() + ' expired batches in active stock, ' + expiringCount.toString() + ' expiring within 90 days, '\n"
  "          + criticalRiskCount.toString() + ' flagged critical by ML model. Be factual and action-oriented.';\n"
  "      final response = await _model!.generateContent([Content.text(prompt)]).timeout(const Duration(seconds: 8));\n"
  "      final result = response.text?.trim();\n"
  "      if (result != null && result.isNotEmpty) return result;\n"
  "    } catch (e) {\n"
  "      debugPrint('Expiry briefing error: ' + e.toString());\n"
  "    }\n"
  "    return _offlineExpiryBriefing(expiringCount: expiringCount, expiredCount: expiredCount,\n"
  "        criticalRiskCount: criticalRiskCount, organizationName: organizationName);\n"
  "  }\n"
  "\n"
  "  String _offlineExpiryBriefing({required int expiringCount, required int expiredCount,\n"
  "      required int criticalRiskCount, required String organizationName}) {\n"
  "    if (expiredCount == 0 && expiringCount == 0) {\n"
  "      return 'All inventory at ' + organizationName + ' is within CDSCO compliance.';\n"
  "    }\n"
  "    final parts = <String>[];\n"
  "    if (expiredCount > 0) parts.add(expiredCount.toString() + ' batch' + (expiredCount > 1 ? 'es' : '') + ' have expired and must be returned immediately');\n"
  "    if (expiringCount > 0) parts.add(expiringCount.toString() + ' batch' + (expiringCount > 1 ? 'es are' : ' is') + ' expiring within 90 days');\n"
  "    return parts.join('. ') + '. ML risk engine flags ' + criticalRiskCount.toString() + ' as critical priority.';\n"
  "  }\n"
)

with open('lib/services/gemini_service.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# Find insertion point: before the closing } of the GeminiService class
# The closing is `  }\n}` right before `class PackagingValidationResult`
insertion_marker = '  }\n}\n\nclass PackagingValidationResult'
idx = content.find(insertion_marker)
if idx == -1:
    print('ERROR: marker not found')
    sys.exit(1)

# Insert after the `  }` of _getMockNarrative, before the class `}`
insert_pos = idx + 3  # after '  }'
new_content = content[:insert_pos] + new_methods + '\n' + content[insert_pos:]

with open('lib/services/gemini_service.dart', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done. New size:', len(new_content))
